GEE_JSON = '''
{
  "type": "service_account",
  "project_id": "winged-plate-496806-p9",
  "private_key_id": "...",
  "private_key": "...",
  "client_email": "streamlit-gee@winged-plate-496806-p9.iam.gserviceaccount.com"
}
'''